apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: jenkins
        podLabels:
          app.kubernetes.io/name: jenkins
        gateway: tenant
        host: jenkins
        port: 8080
    allow:
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: jenkins
        port: 443
        description: "Jenkins-plugins"
