apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Jenkins SSO
      clientId: uds-core-jenkins
      redirectUris:
        - "https://jenkins.{{ .Values.domain }}/users/auth/openid_connect/callback"
  {{- end }}
  network:
    expose:
      - service: jenkins
        podLabels:
          app.kubernetes.io/name: jenkins
        gateway: tenant
        host: jenkins
        port: 8080
    allow:
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: jenkins
        port: 443
        description: "Jenkins-plugins"
