tasks:
  - name: cluster
    actions:
      - description: Destroy k3d cluster
        cmd: k3d cluster delete uds

  - name: bundle
    actions:
      - description: Remove the Deployed UDS Jenkins Bundle
        cmd: ./uds remove ./bundle/uds-bundle-jenkins-test*.tar.zst --confirm --no-progress
