tasks:
  - name: jenkins-test-bundle
    description: Create the UDS bundle with Jenkins and its dependencies
    actions:
      - task: jenkins-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: jenkins-package
    description: Create the UDS Jenkins Zarf Package
    actions:
      - cmd: zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE}
