variables:
  - name: TARGET_REPO
    default: oci://ghcr.io/defenseunicorns/packages/uds

  - name: VERSION
    description: The version of the package to build
    # x-release-please-start-version
    default: "4.3.9-uds.0"
    # x-release-please-end

  - name: FLAVOR
    default: "registry1"

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - description: Create the packages
        cmd: |
          set -e
          ZARF_ARCHITECTURE=amd64 uds run -f tasks/create.yaml jenkins-package --no-progress --set FLAVOR=${FLAVOR}
          if [ ${FLAVOR} != "registry1" ]; then
            ZARF_ARCHITECTURE=arm64 uds run -f tasks/create.yaml jenkins-package --no-progress --set FLAVOR=${FLAVOR}
          fi
      
      - description: Publish the packages
        cmd: |
          set -e
          zarf package publish zarf-package-jenkins-amd64-${VERSION}.tar.zst ${TARGET_REPO}
          if [ ${FLAVOR} != "registry1" ]; then
           zarf package publish zarf-package-jenkins-arm64-${VERSION}.tar.zst ${TARGET_REPO}
          fi