tasks:
  - name: health-check
    actions:
      - description: Jenkins StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: jenkins
            namespace: jenkins

  - name: ingress
    actions:
      - description: Jenkins UI Health Check
        wait:
          network:
            protocol: https
            address: jenkins.uds.dev/login
            code: 200

  - name: ui
    description: Jenkins UI Checks
    actions:
      - cmd: npm ci
        dir: tests
      - cmd: npx playwright install --with-deps
        dir: tests
      - cmd: npx playwright test
        dir: tests
