shared:
  domain: "uds.dev"

variables:
  jenkins:
    JENKINS_PVC_SIZE: "50Gi"
    # JENKINS_PLUGINS: '["kubernetes:4238.v41b_3ef14a_5d8", "workflow-aggregator:596.v8c21c963d92d", "git:5.2.2", "configuration-as-code:1810.v9b_c30a_249a_4c", "oic-auth:4.269.va_7526f34f306", "prometheus:773.v3b_62d8178eec", "cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_", "saml:4.464.vea_cb_75d7f5e0"]'
    # JENKINS_PLUGINS:
    #   - kubernetes:4238.v41b_3ef14a_5d8
    #   - workflow-aggregator:596.v8c21c963d92d
    #   - git:5.2.2
    #   - configuration-as-code:1810.v9b_c30a_249a_4c
    #   - oic-auth:4.269.va_7526f34f306
    #   - prometheus:773.v3b_62d8178eec
    #   - cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
    #   - saml:4.464.vea_cb_75d7f5e0
    JENKINS_SSO_ENABLED: true
    JENKINS_SSO_PROTOCOL: "saml"
