# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Metadata

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

jobs:
  validate:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@35643dbcee81bd963fee7c0c5eae937594bd083d # v1.10.2
