# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Metadata

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

jobs:
  validate:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@95f3e890880ccba48053dac5c4b76291291cb929 # v1.9.0
