name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: uds-marketplace-ubuntu-big-boy-4-core
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        flavor: [upstream, registry1, unicorn]
        type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@a7549ad75a9bbd8e71ce2236ec17c1e33ec4df61 # v0.8.1
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@a7549ad75a9bbd8e71ce2236ec17c1e33ec4df61 # v0.8.1
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@a7549ad75a9bbd8e71ce2236ec17c1e33ec4df61 # v0.8.1
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Print cluster info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get nodes -o wide

      - name: Print pod info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get pods -A -o wide

      - name: Print service info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get svc -A -o wide

      - name: Print events
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get events -A -o wide

      - name: Print Jenkins pod logs
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl logs jenkins-0 -n jenkins

      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: playwright-screenshot
          path: tests/screenshots/*

      - name: Upload video on failure
        if: failure()
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: playwright-video
          path: tests/.playwright/output/*
