name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  flavor-test:
    name: Test-Flavor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: test-flavor
        uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        id: test-flavor
    outputs:
      upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}

  deploy-test:
    # TODO: need to fix how actions work in uds-common before this can be used
    # needs: flavor-test
    # permissions: write-all
    # uses: defenseunicorns/uds-common/.github/workflows/test-deploy.yaml@callable_workflow_fix  #@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
    # with:
    #   upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
    #   flavor: ${{ matrix.flavor }}
    #   type: ${{ matrix.type }}
    #   runs-on: ubuntu-latest
    #   clean-runner: false
    #   upload-reports: playwright
    #   timeout: 25
    # secrets: inherit # Inherits all secrets from the parent workflow.
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     type: [install, upgrade]
    #     flavor: [upstream, registry1, unicorn]


    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        flavor: [upstream, registry1, unicorn]
        type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Playwright setup
        uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0

      - name: Test
        uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Print cluster info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get nodes -o wide

      - name: Print pod info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get pods -A -o wide

      - name: Print service info
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get svc -A -o wide

      - name: Print events
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl get events -A -o wide

      - name: Print Jenkins pod logs
        if: always()
        shell: bash -e -o pipefail {0}
        run: |
          kubectl logs jenkins-0 -n jenkins

      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: playwright-screenshot
          path: tests/screenshots/*

      - name: Upload video on failure
        if: failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: playwright-video
          path: tests/.playwright/output/*
